//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Golight.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace analyzer {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="GolightParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IGolightVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="GolightParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] GolightParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GolightParser.instruccion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstruccion([NotNull] GolightParser.InstruccionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GolightParser.bloquessentencias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBloquessentencias([NotNull] GolightParser.BloquessentenciasContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GolightParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaration([NotNull] GolightParser.DeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GolightParser.slices"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSlices([NotNull] GolightParser.SlicesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GolightParser.lista_valores_slicemulti"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLista_valores_slicemulti([NotNull] GolightParser.Lista_valores_slicemultiContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GolightParser.lista_valores"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLista_valores([NotNull] GolightParser.Lista_valoresContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GolightParser.sentenciastransfer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSentenciastransfer([NotNull] GolightParser.SentenciastransferContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GolightParser.seccontrol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSeccontrol([NotNull] GolightParser.SeccontrolContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GolightParser.if"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf([NotNull] GolightParser.IfContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ElseIf</c>
	/// labeled alternative in <see cref="GolightParser.else"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElseIf([NotNull] GolightParser.ElseIfContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ElseBlock</c>
	/// labeled alternative in <see cref="GolightParser.else"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElseBlock([NotNull] GolightParser.ElseBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GolightParser.for"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFor([NotNull] GolightParser.ForContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GolightParser.switch"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitch([NotNull] GolightParser.SwitchContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GolightParser.lista_cases"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLista_cases([NotNull] GolightParser.Lista_casesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GolightParser.case"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCase([NotNull] GolightParser.CaseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GolightParser.funcion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncion([NotNull] GolightParser.FuncionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GolightParser.lista_parametros"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLista_parametros([NotNull] GolightParser.Lista_parametrosContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GolightParser.print"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrint([NotNull] GolightParser.PrintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GolightParser.concatenacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConcatenacion([NotNull] GolightParser.ConcatenacionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GolightParser.incredecre"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIncredecre([NotNull] GolightParser.IncredecreContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GolightParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] GolightParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Logical_OR</c>
	/// labeled alternative in <see cref="GolightParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogical_OR([NotNull] GolightParser.Logical_ORContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MulDiv</c>
	/// labeled alternative in <see cref="GolightParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMulDiv([NotNull] GolightParser.MulDivContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>INT</c>
	/// labeled alternative in <see cref="GolightParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitINT([NotNull] GolightParser.INTContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AccesoArreglo</c>
	/// labeled alternative in <see cref="GolightParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAccesoArreglo([NotNull] GolightParser.AccesoArregloContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Concat</c>
	/// labeled alternative in <see cref="GolightParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConcat([NotNull] GolightParser.ConcatContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AccesoStruct</c>
	/// labeled alternative in <see cref="GolightParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAccesoStruct([NotNull] GolightParser.AccesoStructContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LlamadaFuncion</c>
	/// labeled alternative in <see cref="GolightParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLlamadaFuncion([NotNull] GolightParser.LlamadaFuncionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AccesoArregloMulti</c>
	/// labeled alternative in <see cref="GolightParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAccesoArregloMulti([NotNull] GolightParser.AccesoArregloMultiContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Unario</c>
	/// labeled alternative in <see cref="GolightParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnario([NotNull] GolightParser.UnarioContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ID</c>
	/// labeled alternative in <see cref="GolightParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitID([NotNull] GolightParser.IDContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Equality</c>
	/// labeled alternative in <see cref="GolightParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEquality([NotNull] GolightParser.EqualityContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>RUNE</c>
	/// labeled alternative in <see cref="GolightParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRUNE([NotNull] GolightParser.RUNEContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LlamadaMetodo</c>
	/// labeled alternative in <see cref="GolightParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLlamadaMetodo([NotNull] GolightParser.LlamadaMetodoContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Mod</c>
	/// labeled alternative in <see cref="GolightParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMod([NotNull] GolightParser.ModContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AddSub</c>
	/// labeled alternative in <see cref="GolightParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAddSub([NotNull] GolightParser.AddSubContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FLOAT64</c>
	/// labeled alternative in <see cref="GolightParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFLOAT64([NotNull] GolightParser.FLOAT64Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Relational</c>
	/// labeled alternative in <see cref="GolightParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelational([NotNull] GolightParser.RelationalContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Agrupacion</c>
	/// labeled alternative in <see cref="GolightParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAgrupacion([NotNull] GolightParser.AgrupacionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Logical_AND</c>
	/// labeled alternative in <see cref="GolightParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogical_AND([NotNull] GolightParser.Logical_ANDContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Not</c>
	/// labeled alternative in <see cref="GolightParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNot([NotNull] GolightParser.NotContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FuncionesEmbebidas</c>
	/// labeled alternative in <see cref="GolightParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncionesEmbebidas([NotNull] GolightParser.FuncionesEmbebidasContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ValorExpr</c>
	/// labeled alternative in <see cref="GolightParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValorExpr([NotNull] GolightParser.ValorExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>STRING</c>
	/// labeled alternative in <see cref="GolightParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSTRING([NotNull] GolightParser.STRINGContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AccesoStructLista</c>
	/// labeled alternative in <see cref="GolightParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAccesoStructLista([NotNull] GolightParser.AccesoStructListaContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AgrupacionCorchetes</c>
	/// labeled alternative in <see cref="GolightParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAgrupacionCorchetes([NotNull] GolightParser.AgrupacionCorchetesContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BOOLEANO</c>
	/// labeled alternative in <see cref="GolightParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBOOLEANO([NotNull] GolightParser.BOOLEANOContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GolightParser.lista_expresiones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLista_expresiones([NotNull] GolightParser.Lista_expresionesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GolightParser.funcembebidas"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncembebidas([NotNull] GolightParser.FuncembebidasContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GolightParser.struct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct([NotNull] GolightParser.StructContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GolightParser.lista_valores_struct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLista_valores_struct([NotNull] GolightParser.Lista_valores_structContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GolightParser.listastruct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitListastruct([NotNull] GolightParser.ListastructContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Int</c>
	/// labeled alternative in <see cref="GolightParser.valor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInt([NotNull] GolightParser.IntContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Float64</c>
	/// labeled alternative in <see cref="GolightParser.valor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFloat64([NotNull] GolightParser.Float64Context context);
	/// <summary>
	/// Visit a parse tree produced by the <c>String</c>
	/// labeled alternative in <see cref="GolightParser.valor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString([NotNull] GolightParser.StringContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Rune</c>
	/// labeled alternative in <see cref="GolightParser.valor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRune([NotNull] GolightParser.RuneContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Booleano</c>
	/// labeled alternative in <see cref="GolightParser.valor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBooleano([NotNull] GolightParser.BooleanoContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Id</c>
	/// labeled alternative in <see cref="GolightParser.valor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitId([NotNull] GolightParser.IdContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Nil</c>
	/// labeled alternative in <see cref="GolightParser.valor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNil([NotNull] GolightParser.NilContext context);
}
} // namespace analyzer
