public static class Register
{
    // Registros de propósito general de 64 bits (X0-X30)
    public static string X0 => "x0";
    public static string X1 => "x1";
    public static string X2 => "x2";
    public static string X3 => "x3";
    public static string X4 => "x4";
    public static string X5 => "x5";
    public static string X6 => "x6";
    public static string X7 => "x7";
    public static string X8 => "x8";   // Registro para syscalls
    public static string X9 => "x9";
    public static string X10 => "x10";
    public static string X11 => "x11";
    public static string X12 => "x12";
    public static string X13 => "x13";
    public static string X14 => "x14";
    public static string X15 => "x15";
    public static string X16 => "x16"; // IP0 - Intra-procedure call
    public static string X17 => "x17"; // IP1 - Intra-procedure call
    public static string X18 => "x18"; // Platform register
    public static string X19 => "x19";
    public static string X20 => "x20";
    public static string X21 => "x21";
    public static string X22 => "x22";
    public static string X23 => "x23";
    public static string X24 => "x24";
    public static string X25 => "x25";
    public static string X26 => "x26";
    public static string X27 => "x27";
    public static string X28 => "x28";
    public static string X29 => "x29"; // FP - Frame pointer
    public static string X30 => "x30"; // LR - Link register

    // Registros especiales
    public static string SP => "sp";   // Stack pointer
    public static string FP => "fp";   // Alias para X29
    public static string LR => "lr";   // Alias para X30
    public static string PC => "pc";   // Program counter
    public static string XZR => "xzr"; // Zero register (64-bit)

    // Registros de propósito general de 32 bits (W0-W30)
    public static string W0 => "w0";
    public static string W1 => "w1";
    public static string W2 => "w2";
    public static string W3 => "w3";
    public static string W4 => "w4";
    public static string W5 => "w5";
    public static string W6 => "w6";
    public static string W7 => "w7";
    public static string W8 => "w8";
    public static string W9 => "w9";
    public static string W10 => "w10";
    public static string W11 => "w11";
    public static string W12 => "w12";
    public static string W13 => "w13";
    public static string W14 => "w14";
    public static string W15 => "w15";
    public static string W16 => "w16";
    public static string W17 => "w17";
    public static string W18 => "w18";
    public static string W19 => "w19";
    public static string W20 => "w20";
    public static string W21 => "w21";
    public static string W22 => "w22";
    public static string W23 => "w23";
    public static string W24 => "w24";
    public static string W25 => "w25";
    public static string W26 => "w26";
    public static string W27 => "w27";
    public static string W28 => "w28";
    public static string W29 => "w29";
    public static string W30 => "w30";
    public static string WZR => "wzr"; // Zero register (32-bit)

    // Registros de punto flotante/vectoriales de 64 bits (D0-D31)
    public static string D0 => "d0";
    public static string D1 => "d1";
    public static string D2 => "d2";
    public static string D3 => "d3";
    public static string D4 => "d4";
    public static string D5 => "d5";
    public static string D6 => "d6";
    public static string D7 => "d7";
    public static string D8 => "d8";
    public static string D9 => "d9";
    public static string D10 => "d10";
    public static string D11 => "d11";
    public static string D12 => "d12";
    public static string D13 => "d13";
    public static string D14 => "d14";
    public static string D15 => "d15";
    public static string D16 => "d16";
    public static string D17 => "d17";
    public static string D18 => "d18";
    public static string D19 => "d19";
    public static string D20 => "d20";
    public static string D21 => "d21";
    public static string D22 => "d22";
    public static string D23 => "d23";
    public static string D24 => "d24";
    public static string D25 => "d25";
    public static string D26 => "d26";
    public static string D27 => "d27";
    public static string D28 => "d28";
    public static string D29 => "d29";
    public static string D30 => "d30";
    public static string D31 => "d31";

    // Registros de punto flotante/vectoriales de 32 bits (S0-S31)
    public static string S0 => "s0";
    public static string S1 => "s1";
    public static string S2 => "s2";
    public static string S3 => "s3";
    public static string S4 => "s4";
    public static string S5 => "s5";
    public static string S6 => "s6";
    public static string S7 => "s7";
    public static string S8 => "s8";
    public static string S9 => "s9";
    public static string S10 => "s10";
    public static string S11 => "s11";
    public static string S12 => "s12";
    public static string S13 => "s13";
    public static string S14 => "s14";
    public static string S15 => "s15";
    public static string S16 => "s16";
    public static string S17 => "s17";
    public static string S18 => "s18";
    public static string S19 => "s19";
    public static string S20 => "s20";
    public static string S21 => "s21";
    public static string S22 => "s22";
    public static string S23 => "s23";
    public static string S24 => "s24";
    public static string S25 => "s25";
    public static string S26 => "s26";
    public static string S27 => "s27";
    public static string S28 => "s28";
    public static string S29 => "s29";
    public static string S30 => "s30";
    public static string S31 => "s31";
}